<!DOCTYPE html>
<html>
<head>
<title>Welcome Letter</title>
</head>
<body>
	<h3>Dear Admin,</h3>

	<p>A warm welcome and lots of good wishes on becoming part of our growing team.</p>
	<p>We are pleased to inform you that you will work with the following team members:</p>
	<ol>

	<p> ${name} has been blocked !!</p>

	</ol>
	<p>Regards</p>
	<p>Backend Team</p>
	<p>Location: Bengaluru</p>
</body>
</html>